import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { forkJoin, map, of, switchMap } from 'rxjs';
import { ApiService, ConflictDto, PersonDto } from '../api.service';

type JsonObject = any;

@Component({selector:'app-editor-json-import',imports:[FormsModule,RouterLink],template:`<main class="editor-shell"><header class="editor-header"><a [routerLink]="targetId?['/editor/conflicts',targetId]:['/editor']"><b>← {{targetId?'Материал':'Материалы'}}</b></a><button class="button primary" type="button" (click)="submitImport()" [disabled]="loading()">{{loading()?(targetId?'Обновление...':'Создание...'):(targetId?'Обновить материал':'Создать черновик')}}</button></header><section class="panel"><span class="muted">{{targetId?'ОБНОВЛЕНИЕ ИЗ JSON':'ИМПОРТ JSON'}}</span><h1>{{targetId?'Обновить материал из JSON':'Создать материал из JSON'}}</h1><p class="muted">Поддерживается полный объект с people_catalog и conflict, а также готовый объект конфликта. Импорт никогда не публикует материал автоматически. При обновлении изменяется текущий материал, новый не создается.</p><label>Выбрать JSON-файл<input type="file" accept="application/json,.json" (change)="readFile($any($event.target))"></label><br><label>JSON<textarea class="json-input" rows="24" [(ngModel)]="json" spellcheck="false" placeholder='{"people_catalog":[],"conflict":{}}'></textarea></label>@if(error()){<p class="error">{{error()}}</p>}@if(summary()){<div class="import-summary"><b>{{summary()!.title}}</b><span>{{summary()!.events}} событий</span><span>{{summary()!.people}} связей</span><span>{{summary()!.catalog}} записей в справочнике</span></div>}</section></main>`,styleUrl:'./editor.scss'})
export class EditorJsonImport{
 private api=inject(ApiService);private router=inject(Router);private route=inject(ActivatedRoute);protected readonly targetId=Number(this.route.snapshot.queryParamMap.get('conflict'))||null;protected json='';protected error=signal('');protected loading=signal(false);protected summary=signal<{title:string;events:number;people:number;catalog:number}|null>(null);
 protected readFile(input:HTMLInputElement):void{const file=input.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{this.json=String(reader.result||'');this.inspect();};reader.readAsText(file,'utf-8');}
 protected submitImport():void{
  this.error.set('');let root:JsonObject;
  try{root=JSON.parse(this.json);}catch{this.error.set('JSON содержит синтаксическую ошибку');return;}
  const conflict:JsonObject=root['conflict']||root,catalog:JsonObject[]=Array.isArray(root['people_catalog'])?root['people_catalog']:[];
  const problem=this.validate(conflict);if(problem){this.error.set(problem);return;}
  this.loading.set(true);
  forkJoin({people:this.api.people(),conflicts:this.targetId?this.api.adminConflicts():of([] as ConflictDto[])}).pipe(
   switchMap(result=>{const bySlug=new Map(result.people.map(person=>[person.slug,person]));const missing=catalog.filter(person=>person?.slug&&!bySlug.has(person.slug));const people$=missing.length?forkJoin(missing.map(person=>this.api.createPerson(this.personPayload(person)))).pipe(map(created=>[...result.people,...created])):of(result.people);return people$.pipe(map(people=>({people,conflicts:result.conflicts})));}),
   switchMap(({people,conflicts})=>{const payload=this.conflictPayload(conflict,people);if(!this.targetId)return this.api.createConflict(payload);const current=conflicts.find(item=>item.id===this.targetId);if(!current)throw new Error('Материал для обновления не найден');payload.slug=current.slug;return this.api.updateConflict(this.targetId,{...payload,change_description:'Материал обновлен через импорт JSON'});})
  ).subscribe({next:item=>{this.loading.set(false);void this.router.navigate(['/editor/conflicts',item.id]);},error:e=>{this.loading.set(false);const detail=e.error?.detail;this.error.set(typeof detail==='string'?detail:Array.isArray(detail)?detail.map((item:any)=>`${item.loc?.join('.')}: ${item.msg}`).join('\n'):e.message||'Не удалось импортировать материал');}});
 }
 protected inspect():void{try{const root=JSON.parse(this.json),conflict=root.conflict||root;this.summary.set({title:conflict.title||'Без названия',events:Array.isArray(conflict.events)?conflict.events.length:0,people:Array.isArray(conflict.people)?conflict.people.length:0,catalog:Array.isArray(root.people_catalog)?root.people_catalog.length:0});this.error.set('');}catch{this.summary.set(null);}}
 private validate(conflict:JsonObject):string|null{if(!conflict||typeof conflict!=='object')return'Не найден объект conflict';for(const key of ['slug','title','summary','category'])if(!String(conflict[key]||'').trim())return`Не заполнено обязательное поле conflict.${key}`;if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(conflict['slug']))return'Slug должен содержать только латинские буквы, цифры и дефисы';if(!Array.isArray(conflict['events']))return'conflict.events должен быть массивом';if(!Array.isArray(conflict['people']))return'conflict.people должен быть массивом';return null;}
 private personPayload(person:JsonObject):JsonObject{return{slug:person.slug,name:person.name,initials:person.initials||String(person.name||'?').slice(0,2).toUpperCase(),avatar_url:this.cleanUrl(person.avatar_url),bio:person.bio||null,links:Object.fromEntries(Object.entries(person.links||{}).map(([key,value])=>[key,this.cleanUrl(value)||''])),profile_status:person.profile_status==='hidden'?'hidden':'active',entity_type:['streamer','media','organization','other'].includes(person.entity_type)?person.entity_type:'streamer'};}
 private conflictPayload(conflict:JsonObject,people:PersonDto[]):JsonObject{const bySlug=new Map(people.map(person=>[person.slug,person.id]));return{slug:conflict.slug,title:conflict.title,summary:conflict.summary,cover_image_url:this.cleanUrl(conflict.cover_image_url),is_featured:false,priority_enabled:Boolean(conflict.priority_enabled),priority:Math.min(1000,Math.max(0,Number(conflict.priority)||0)),category:conflict.category,status:'draft',next_action:conflict.next_action||null,is_published:false,events:conflict.events.map((event:JsonObject,index:number)=>({occurred_at:this.normalizeDate(event.occurred_at,index),event_type:event.event_type||'update',title:event.title,body:event.body,is_commentary:Boolean(event.is_commentary),position:index,sources:Array.isArray(event.sources)?event.sources.map((source:JsonObject)=>({platform:source.platform,url:this.cleanUrl(source.url),title:source.title||source.platform,source_status:source.source_status||'primary',media_type:['video','post','image','link'].includes(source.media_type)?source.media_type:'link',thumbnail_url:this.cleanUrl(source.thumbnail_url),duration_seconds:source.duration_seconds??null})):[]})),people:conflict.people.map((entry:JsonObject)=>{const id=Number(entry.person_id||bySlug.get(entry.person_slug));if(!id)throw new Error(`Не найден person_slug: ${entry.person_slug}`);return{person_id:id,relation:entry.relation||'participant',role:entry.role||null,event_ids:Array.isArray(entry.event_ids)?entry.event_ids:Array.isArray(entry.event_indexes)?entry.event_indexes:[]};})};}
 private cleanUrl(raw:unknown):string|null{if(raw===null||raw===undefined)return null;const value=String(raw).trim();if(!value)return null;const markdown=value.match(/^\[[^\]]*\]\((https?:\/\/[^)]+)\)$/);return markdown?markdown[1]:value;}
 private normalizeDate(raw:unknown,index:number):string|null{if(raw===null||raw===undefined||String(raw).trim()==='')return null;const value=String(raw).trim();let match;if((match=value.match(/^(\d{4})-(\d{2})-(\d{2})$/)))return`${match[1]}-${match[2]}-${match[3]}T12:00:00+03:00`;if((match=value.match(/^(\d{4}-\d{2}-\d{2})[ T](\d{2}):(\d{2})(?::(\d{2}))?$/)))return`${match[1]}T${match[2]}:${match[3]}:${match[4]||'00'}+03:00`;if((match=value.match(/^(\d{2})\.(\d{2})\.(\d{4})(?:[ ,T]+(\d{2}):(\d{2}))?$/)))return`${match[3]}-${match[2]}-${match[1]}T${match[4]||'12'}:${match[5]||'00'}:00+03:00`;if(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2}(?:\.\d+)?)?(?:Z|[+-]\d{2}:\d{2})$/.test(value)&&!Number.isNaN(Date.parse(value)))return value;throw new Error(`Событие ${index+1}: некорректная дата "${value}". Используйте YYYY-MM-DD или ISO 8601.`);}
}
