import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ApiService, PersonDto } from '../api.service';

@Component({selector:'app-editor-person-form',imports:[FormsModule,RouterLink],template:`<main class="editor-shell"><header class="editor-header"><a routerLink="/editor/people"><b>← Справочник</b></a><button class="button primary" (click)="save()" [disabled]="saving()">Сохранить</button></header>@if(error()){<p class="error">{{error()}}</p>}@if(message()){<p class="success">{{message()}}</p>}<section class="panel"><span class="muted">{{id?'РЕДАКТИРОВАНИЕ':'НОВАЯ ЗАПИСЬ'}}</span><h1>{{model.name||'Новая запись'}}</h1><p class="muted">Язык карточки: {{(model.site_lang||'ru').toUpperCase()}}. Он задаётся сайтом, на котором запись создана, и определяет, где она видна публично.</p><div class="grid"><label>Название или имя<input [(ngModel)]="model.name"></label><label>Slug<input [(ngModel)]="model.slug"></label><label>Инициалы<input [(ngModel)]="model.initials" maxlength="8"></label><label>Тип<select [(ngModel)]="model.entity_type"><option value="streamer">Стример</option><option value="media">Медиа</option><option value="organization">Организация</option><option value="other">Другое</option></select></label><label>Статус<select [(ngModel)]="model.profile_status"><option value="active">Активен</option><option value="hidden">Скрыт</option></select></label><label>Общий ключ RU и EN<input [(ngModel)]="model.canonical_key" placeholder="justin-kan"><small class="muted">Связывает эту карточку с её двойником в другом языке. Нужен истории стриминга: она общая для обоих сайтов.</small></label></div><br><label>Описание<textarea rows="6" [(ngModel)]="model.bio"></textarea></label><br><div class="avatar-editor">@if(model.avatar_url){<img [src]="model.avatar_url" alt="Предпросмотр аватара">}@else{<span>{{model.initials||'?'}}</span>}<div><label>Ссылка на аватар или логотип<input type="url" [(ngModel)]="model.avatar_url" placeholder="https://..."></label><label>Или загрузить файл<input type="file" accept="image/jpeg,image/png,image/webp" (change)="upload($any($event.target))"></label></div></div><br><div class="grid">@for(key of linkKeys;track key){<label>{{key}}<input [(ngModel)]="model.links[key]" placeholder="https://"></label>}</div></section></main>`,styleUrl:'./editor.scss'})
export class EditorPersonForm{
 private api=inject(ApiService);private router=inject(Router);protected id=Number(inject(ActivatedRoute).snapshot.paramMap.get('id'))||null;protected saving=signal(false);protected error=signal('');protected message=signal('');protected linkKeys=['Twitch','Kick','YouTube','Telegram','X'];
 protected model:any={slug:'',name:'',initials:'',avatar_url:'',bio:'',links:{Twitch:'',Kick:'',YouTube:'',Telegram:'',X:''},profile_status:'active',entity_type:'streamer',canonical_key:''};
 constructor(){if(this.id)this.api.searchPeople('',true).subscribe(items=>{const item=items.find(x=>x.id===this.id);if(item)this.model={...item,canonical_key:item.canonical_key||'',links:{...this.model.links,...item.links}}})}
 protected upload(input:HTMLInputElement){const file=input.files?.[0];if(file)this.api.uploadImage(file).subscribe({next:r=>this.model.avatar_url=r.url,error:()=>this.error.set('Не удалось загрузить аватар')})}
 protected save(){this.saving.set(true);this.error.set('');const payload={...this.model,avatar_url:this.model.avatar_url||null,bio:this.model.bio||null,canonical_key:this.model.canonical_key?.trim()||null,links:Object.fromEntries(Object.entries(this.model.links).filter(([,v])=>v))};const request=this.id?this.api.updatePerson(this.id,payload):this.api.createPerson(payload);request.subscribe({next:item=>{this.saving.set(false);this.message.set('Сохранено');if(!this.id)void this.router.navigate(['/editor/people',item.id])},error:e=>{this.saving.set(false);this.error.set(e.error?.detail||'Не удалось сохранить профиль')}})}
}
